### ISSUE TITLE
Unnecessary text files

### ISSUE THREAD

**Issue by MeyAyre** [MeyAyre/SpicyShrimpBIT286#7]
Description: Unnecessary text files are cluttering the work space and need to be removed.

Repo Steps: 
 
        1. Open solution in Visual Studio
        2. Expand Solution Explorer
![image](https://user-images.githubusercontent.com/14324873/40018190-68b8e9de-5770-11e8-8846-ba337b0d3049.png)

**Comment by MeyAyre** [comment]
#9  fixed this

**Comment by MikeTheGreat** [comment]
Excellent!

**Comment by MikeTheGreat** [comment]
Also - Golly Gee Wilikers the notifications about GitHub comments show up quickly in Slack.  I feel like I get the slack notification before I finish raising my finger off my mouse button :)
